services:

  db:
    build: ./db
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  app:
    build: ./app
    env_file: .env
    depends_on:
      - db
    networks:
      - backend

  nginx:
    build: ./nginx
    env_file: .env
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend: