services:

  nginx:
    build: ./requirements/nginx
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - backend
    volumes:
      - wp_data:/var/www/html
    restart: always

  wordpress:
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    networks:
      - backend
    volumes:
      - wp_data:/var/www/html
    restart: always

  mariadb:
    build: ./requirements/mariadb
    env_file: .env
    networks:
      - backend
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

volumes:
  wp_data:
    driver_opts:
      type: none
      o: bind
      device: /home/ccolin/data/wp_data
  mariadb_data:
    driver_opts:
      type: none
      o: bind
      device: /home/ccolin/data/mariadb_data


networks:
  backend: