services:

  nginx:
    build: ./requirements/nginx
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - backend
    volumes:
      - wp_data:/var/www/html

  wordpress:
    build: ./requirements/wordpress
    networks:
      - backend
    volumes:
      - wp_data:/var/www/html

volumes:
  wp_data: {}

networks:
  backend: